create table roles (
                       id int8 generated by default as identity,
                       title varchar(255),
                       primary key (id)
);

create table students_tbl (
                              id int8 generated by default as identity,
                              age_fld int4,
                              name_fld varchar(255),
                              primary key (id)
);

create table users (
                       id int8 generated by default as identity,
                       password varchar(255),
                       username varchar(255),
                       primary key (id)
);

create table users_roles (
                             user_id int8 not null,
                             role_id int8 not null
);

alter table if exists users_roles
    add constraint FKj6m8fwv7oqv74fcehir1a9ffy
        foreign key (role_id)
            references roles;

alter table if exists users_roles
    add constraint FK2o0jvgh89lemvvo17cbqvdxaa
        foreign key (user_id)
            references users;

